---
resources:
- name: hello_resource
  type: git
  source:
    uri: https://github.com/making/hello-concourse.git
jobs:
- name: hello-job
  public: true # UI上でJobの結果をログイン不要で公開するかどうか
  plan:
  - get: hello_resource
    trigger: true # Resourceに変更があれば自動でジョブを実行するかどうか
  - task: run-hello
    file: hello/hello.yml
